Fixed load race condition
If loadAnimation issues the load_composition event before returning from the invokeMethod call, there will be no _pendingAnimationLoader waiting for it.

This has been observed fairly often, resulting in uncaught zone exceptions with message "NoSuchMethodError: The method 'complete' was called on null.
Receiver: null
Tried calling: complete(0)" and stack trace
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Fluttie._onData (package:fluttie/fluttie.dart:204:19)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)